service: my-express-application

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'